openapi: 3.0.1
info:
  title: ChartLyrics API
  description: API to search for song lyrics. ChartLyrics carries a comprehensive collection of song lyrics.
  version: 1.0.1
servers:
  - url: http://api.chartlyrics.com/apiv1.asmx
paths:
  /SearchLyric:
    get:
      tags:
        - lyrics
      summary: Search Songs.
      operationId: searchSongs
      parameters:
        - $ref: "#/components/parameters/contentType"
        - name: artist
          in: query
          required: true
          schema:
            type: string
        - name: song
          in: query
          required: true
          schema:
            type: string   
      responses:
        '200':
          description: Success
        
  /SearchLyricText:
    get:
      tags:
        - lyrics
      summary: Search songs by partially matching the lyric.
      operationId: searchSongsByLyrics
      parameters:
        - $ref: "#/components/parameters/contentType"
        - name: lyricText
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success

  /SearchLyricDirect:
    get:
      tags:
        - lyrics
      summary: Fetch the Lyric from a Search Top Result.
      operationId: getLyricFromTopSearchResult
      parameters:
        - $ref: "#/components/parameters/contentType"
        - name: artist
          in: query
          required: true
          schema:
            type: string
        - name: song
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          
  /GetLyric:
    get:
      tags:
        - lyrics
      operationId: getLyric
      parameters:
        - $ref: "#/components/parameters/contentType"
        - name: lyricId
          in: query
          required: true
          schema:
            type: string
        - name: lyricCheckSum
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          
components:
  parameters:
    contentType:
      name: Content-type
      in: header
      default: "text/xml"
      description: "Explicitly provide this parameter with 'text/xml'"
      schema:
        type: string
        enum:
          - "text/xml"
      required: true