openapi: 3.0.3
info:
  title: Newcastle Urban Observatory (UK) - OpenAPI 3.0
  description: |-
    Newcastle Urban Observatory (UK) - OpenAPI specification
    
    Some useful links:
    - [Newcastle Urban Observatory Site](https://urbanobservatory.ac.uk)

  contact:
    email: rauber@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: API Docs
  url: https://newcastle.urbanobservatory.ac.uk/api_docs/
servers:
  - url: https://newcastle.urbanobservatory.ac.uk/api/v1.1
tags:
  - name: sensors
    description: Sensors Endpoints
paths:
  /themes/json/:
    get:
      tags:
        - sensors
      summary: Theme Information
      description: Get all theme names.
      operationId: getThemes
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Themes:
                    type: array
                    items:
                      type: object
                      properties:
                        Name:
                          type: string
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
  /variables/json/:
    get:
      tags:
        - sensors
      summary: Variables available
      description: Get theme variables.
      operationId: getVariables
      parameters:
        - name: theme
          in: query
          description: Filter variables by theme.
          required: false
          schema:
            type: string
            example: "Weather"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Variables:
                    type: array
                    items:
                      type: object
                      properties:
                        Name:
                          type: string
                        Units:
                          type: string
                        Theme:
                          type: string
                        Upper Limit: 
                          type: string
                        Lower Limit:
                          type: string
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
  /sensors/json/:
    get:
      tags:
        - sensors
      summary: Sensor information
      description: Get sensors.
      operationId: getSensors
      parameters:
        - name: theme
          in: query
          description: Filter variables by theme.
          required: false
          schema:
            type: string
            example: "Weather"
        - name: sensor_type
          in: query
          description: Filter information by sensor type.
          required: false
          schema:
            type: string
            example: "NO2"
        - name: broker
          in: query
          description: Filter information by their broker/manufacturer.
          required: false
          schema:
            type: string
            example: "Emote Air Quality Sensor"
        - name: polygon_wkb
          in: query
          description: "Polygon that the sensor falls in Well-Known Binary (WKB) Format"
          required: false
          schema:
            type: string
            example: "01030000000100000005000000ffffffff3f9"
        - name: bbox_p1_x
          in: query
          description: Bounding Box P1-X
          required: false
          schema:
            type: number
            example: -1.4
        - name: bbox_p1_y
          in: query
          description: Bounding Box P1-Y
          required: false
          schema:
            type: number
            example: 55.4
        - name: bbox_p2_x
          in: query
          description: Bounding Box P2-X
          required: false
          schema:
            type: number
            example: -1.2
        - name: bbox_p2_y
          in: query
          description: Bounding Box P2-Y
          required: false
          schema:
            type: number
            example: 56.1
        - name: subset_layer
          in: query
          description: "Region sensor lies inside of"
          required: false
          schema:
            type: string
            example: "Post code Sectors"
        - name: subset_shapes
          in: query
          description: "Region sensor lies inside of"
          required: false
          schema:
            type: string
            example: "NE10 0"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Sensors:
                    type: array
                    items:
                      type: object
                      properties:
                        Sensor Centroid Longitude:
                          type: string
                        Sensor Centroid Latitude:
                          type: string
                        Third Party:
                          type: boolean
                        Sensor Name: 
                          type: string
                        Location (WKT):
                          type: string
                        Sensor Height Above Ground:
                          type: number
                        Raw ID:
                          type: string
                        Ground Height Above Sea Level:
                          type: number
                        Broker Name:
                          type: string
        '400':
          description: Invalid status value
        default:
          description: Unexpected error
  /sensors/data/json/:
    get:
      tags:
        - sensors
      summary: Sensor Data
      description: Get sensors.
      operationId: getSensorsData
      parameters:
        - name: data_variable
          in: query
          description: "Variables to retrieve data for"
          required: false
          schema:
            type: string
            example: "Temperature"
        - name: last_n_days
          in: query
          description: "Selects Data from the last n days"
          required: false
          schema:
            type: integer
            example: 3
        - name: last_n_records
          in: query
          description: "Select the number of latest records to retrieve"
          required: false
          schema:
            type: integer
            example: 200
        - name: starttime
          in: query
          description: "Time slice for which data is queried. Format: **%Y%m%d%H%M%S** or **%Y%m%d**"
          required: false
          schema:
            type: string
            example: "20150101"
        - name: endtime
          in: query
          description: "Time slice for which data is queried. Format: **%Y%m%d%H%M%S** or **%Y%m%d**" 
          required: false
          schema:
            type: string
            example: "20150101"
        - name: theme
          in: query
          description: Filter variables by theme.
          required: false
          schema:
            type: string
            example: "Weather"
        - name: sensor_type
          in: query
          description: Filter information by sensor type.
          required: false
          schema:
            type: string
            example: "NO2"
        - name: broker
          in: query
          description: Filter information by their broker/manufacturer.
          required: false
          schema:
            type: string
            example: "Emote Air Quality Sensor"
        - name: polygon_wkb
          in: query
          description: "Polygon that the sensor falls in Well-Known Binary (WKB) Format"
          required: false
          schema:
            type: string
            example: "01030000000100000005000000ffffffff3f9"
        - name: bbox_p1_x
          in: query
          description: Bounding Box P1-X
          required: false
          schema:
            type: number
            example: -1.4
        - name: bbox_p1_y
          in: query
          description: Bounding Box P1-Y
          required: false
          schema:
            type: number
            example: 55.4
        - name: bbox_p2_x
          in: query
          description: Bounding Box P2-X
          required: false
          schema:
            type: number
            example: -1.2
        - name: bbox_p2_y
          in: query
          description: Bounding Box P2-Y
          required: false
          schema:
            type: number
            example: 56.1
        - name: subset_layer
          in: query
          description: "Region sensor lies inside of"
          required: false
          schema:
            type: string
            example: "Post code Sectors"
        - name: subset_shapes
          in: query
          description: "Region sensor lies inside of"
          required: false
          schema:
            type: string
            example: "NE10 0"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  Sensors:
                    type: array
                    items:
                      type: object
                      properties:
                        data:
                          type: object
                        Sensor Centroid Longitude:
                          type: string
                        Sensor Centroid Latitude:
                          type: string
                        Third Party:
                          type: boolean
                        Sensor Name: 
                          type: string
                        Location (WKT):
                          type: string
                        Sensor Height Above Ground:
                          type: number
                        Raw ID:
                          type: string
                        Ground Height Above Sea Level:
                          type: number
                        Broker Name:
                          type: string
        '400':
          description: Invalid status value
        default:
          description: Unexpected error