openapi: 3.0.3
info:
  title: Numbers API - OpenAPI 3.0
  description: "Bring meaning to your metrics and stories to your dates with an API of interesting number facts."
  contact:
    email: rauber@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
externalDocs:
  description: Numbers API Docs
  url: http://numbersapi.com
servers:
  - url: http://numbersapi.com
tags:
  - name: numbers
    description: Numbers Endpoints
paths:
  /{number}/{type}:
    get:
      tags:
        - numbers
      summary: "Get facts about a number or a date."
      operationId: getFactsAboutNumberOrDate
      parameters:
        - name: number
          in: path
          description: >-
            number can be an integer; 
            or the keyword **random**, for which we will try to return a random available fact; 
            or a day of year in the form month/day (eg. 2/29, 1/09, 04/1), if type is date; 
            or ranges of numbers. 
            To get facts about multiple numbers in one request, specify ranges. 
            A number range (inclusive) is specified as **min..max**. Separate multiple ranges and individual numbers with a comma.
          required: true
          schema:
            type: string
            example: "random"
        - name: type
          in: path
          description: "Number Type"
          required: true
          schema:
            type: string
            default: "trivia"
            enum:
            - trivia
            - math
            - date
            - year
        - name: json
          in: query
          required: true
          description: "Supply the parameter to return the response in json format. Not necessary if a content-type header is supplied."
          schema:
            type: string
            default: "json"
        - name: notfound
          in: query
          description: "What to do if the number is not found. You can use: **default** to return one of the pre-written missing messages, or a message you supply with the default query field. This is the default behaviour. **floor** to round down to the largest number that does have an associated fact. **ceil**, which is like floor but rounds up to the smallest number that has an associated fact."
          required: false
          schema:
            type: string
            enum:
            - default
            - floor
            - ceil 
        - name: default
          in: query
          description: "`default` value to return if a fact for the requested number isn't found. (eg:not found)"
          required: false
          schema:
            type: string
            example: "Boring+number+is+boring"
        - name: min
          in: query
          description: "Lower limit when 'random' is used as the number."
          required: false
          schema:
            type: integer
            example: 10
        - name: max
          in: query
          description: "Upper limit when 'random' is used as the number."
          required: false
          schema:
            type: integer
            example: 20
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Number'
components:
  schemas:
    Number:
      type: object
      properties:
        text:
          type: string
        year:
          type: integer
        number:
          type: integer
        found:
          type: boolean
        type:
          type: string
      xml:
        name: number